### ISSUE TITLE
No object named 'Meccano' found in 'DATASET' registry

### ISSUE THREAD

**Issue by aranciokov** [fpv-iplab/MECCANO#11]
Hi, thanks for releasing this interesting project. I'm trying to work on the action recognition task. So far, I have done the following:

* installed PySlowFast following the official repo (PYTHONPATH contains the link to the slowfast folder)
* slowfast/datasets contains __init__.py, meccano.py and sampling.py; whereas slowfast/models contains custom_video_model_builder_MECCANO_gaze.py and __init__.py
* I downloaded videos, rgb frames, and temporal annotations into a folder called 'data', which is located on the same level of slowfast (i.e., from the slowfast folder I can list the contents of data by 'ls ../data'); the folder 'data' contains a folder Meccano, which contains the folders MECCANO_RGB_Videos and RGB_frames, and three files: MECCANO_train_actions.csv, MECCANO_test_actions.csv, MECCANO_val_actions.csv
* in the config file located at ../configs/action_recognition/SLOWFAST_8x8_R50_MECCANO.yaml I set the PATH_TO_DATA_DIR to ../data

Now, to the problem. When I execute "python tools/run_net.py --cfg ../configs/action_recognition/SLOWFAST_8x8_R50_MECCANO.yaml" I get the following error: 
> Traceback (most recent call last):
>  File "/media/HDD/alexfalcon/MECCANO/env_meccano/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
>    fn(i, *args)
> File "/media/HDD/alexfalcon/MECCANO/slowfast/slowfast/utils/multiprocessing.py", line 60, in run
>     ret = func(cfg)
>   File "/media/HDD/alexfalcon/MECCANO/slowfast/tools/train_net.py", line 596, in train
>     train_loader = loader.construct_loader(cfg, "train")
>   File "/media/HDD/alexfalcon/MECCANO/slowfast/slowfast/datasets/loader.py", line 114, in construct_loader
>     dataset = build_dataset(dataset_name, cfg, split)
>   File "/media/HDD/alexfalcon/MECCANO/slowfast/slowfast/datasets/build.py", line 31, in build_dataset
>     return DATASET_REGISTRY.get(name)(cfg, split)
>   File "/media/HDD/alexfalcon/MECCANO/env_meccano/lib/python3.8/site-packages/fvcore/common/registry.py", line 71, in get
>     raise KeyError(
> KeyError: "No object named 'Meccano' found in 'DATASET' registry!"

Unfortunately, I can't seem to figure out the cause of this issue. Any idea?
Thanks and cheers,
Alex

**Comment by francescoragusa** [comment]
Hi @aranciokov, 
thank you for your interest about our work!

It seems strange that the error that you described occurs.
To avoid that error, it is fundamental to replace the `__init__.py` file  in the "slowfast/datasets/" folder  where the Meccano class is imported:

`from .meccano import Meccano #added`

Can you check that in your `/slowfast/datasets/__init__.py` file there is that "import"?
